name: HAHA

on:
  workflow_dispatch:
  schedule:
     - cron: '10 0-15 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_iboxpayHEADER: ${{ secrets.XP_iboxpayHEADER2 }}
        XP_CASH: ${{ secrets.XP_CASH }}
        XP_live: ${{ secrets.XP_live }} 
        XP_refreshTOKEN: ${{ secrets.XP_REFRESHTOKEN2 }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/WWS321/6UmRS-sbs3W-.git ~/bbb
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/bbb
          git checkout bupJS
          npm install
      - name: '运行 【XIXI】'
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/bbb
          node Task/iboxpay.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
