# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: XIXI

on:
  workflow_dispatch:
  schedule:
     - cron: '*/5 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_iboxpayHEADER: ${{ secrets.XP_iboxpayHEADER }}
        XP_CASH: ${{ secrets.XP_CASH }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XP_iboxpayHEADER
        run: |
          npm install --save got
      - name: '运行 【XIXI】'
        if: env.XP_iboxpayHEADER
        run: |
          node Task/XPZB.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


   
