name: jdtqqqqq

on:
  workflow_dispatch:
  schedule:
     - cron: '6 0-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JDTQ_jdtquserBODY: ${{ secrets.JDTQ_jdtquserBODY }}
        JDTQ_jdtqcoinBODY: ${{ secrets.JDTQ_jdtqcoinBODY }}
        JDTQ_jdtqqpBODY: ${{ secrets.JDTQ_jdtqqpBODY }}
        JDTQ_jdtqqp1BODY: ${{ secrets.JDTQ_jdtqqp1BODY }}
        JDTQ_jdtqqp1fbBODY: ${{ secrets.JDTQ_jdtqqp1fbBODY }}
        JDTQ_jdtqqp2BODY: ${{ secrets.JDTQ_jdtqqp2BODY }}
        JDTQ_jdtqqp2fbBODY: ${{ secrets.JDTQ_jdtqqp2fbBODY }}
        JDTQ_jdtqqp3BODY: ${{ secrets.JDTQ_jdtqqp3BODY }}
        JDTQ_jdtqqp3fbBODY: ${{ secrets.JDTQ_jdtqqp3fbBODY }}
        JDTQ_jdtqqp4BODY: ${{ secrets.JDTQ_jdtqqp4BODY }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/WWS321/6UmRS-sbs3W-.git ~/bbb
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.JDTQ_jdtquserBODY
        run: |
          cd ~/bbb
          git checkout bupJS
          npm install
      - name: '运行 【jdtqqqqq】'
        if: env.JDTQ_jdtquserBODY
        run: |
          cd ~/bbb
          node Task/jdtq.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
