name: yqnbbbb

on:
  workflow_dispatch:
  schedule:
     - cron: ' 7 15-4 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YQNB_yqnbHEADER: ${{ secrets.YQNB_yqnbHEADER }}
        YQNB_yqnbBODY: ${{ secrets.YQNB_yqnbBODY }}

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/WWS321/6UmRS-sbs3W-.git ~/bbb
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YQNB_yqnbHEADER
        run: |
          cd ~/bbb
          git checkout bupJS
          npm install
      - name: '运行 【yqnbbbb】'
        if: env.YQNB_yqnbHEADER
        run: |
          cd ~/bbb
          node Task/yqnb.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
